/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutenticadoRouteImport } from './routes/_autenticado'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AutenticadoPainelRouteImport } from './routes/_autenticado.painel'
import { Route as AutenticadoModuloSlugRouteImport } from './routes/_autenticado.modulo.$slug'
import { Route as AutenticadoModuloAdministracaoRouteImport } from './routes/_autenticado.modulo.administracao'
import { Route as AutenticadoModuloCaixaRouteImport } from './routes/_autenticado.modulo.caixa'
import { Route as AutenticadoModuloEncomendasRouteImport } from './routes/_autenticado.modulo.encomendas'
import { Route as AutenticadoModuloImoveisRouteImport } from './routes/_autenticado.modulo.imoveis'
import { Route as AutenticadoModuloLogsRouteImport } from './routes/_autenticado.modulo.logs'
import { Route as AutenticadoModuloManutencaoRouteImport } from './routes/_autenticado.modulo.manutencao'
import { Route as AutenticadoModuloPessoasRouteImport } from './routes/_autenticado.modulo.pessoas'
import { Route as AutenticadoModuloPreCadastroRouteImport } from './routes/_autenticado.modulo.pre-cadastro'
import { Route as AutenticadoModuloPrestadoresRouteImport } from './routes/_autenticado.modulo.prestadores'
import { Route as AutenticadoModuloRelatoriosRouteImport } from './routes/_autenticado.modulo.relatorios'
import { Route as AutenticadoModuloValidacaoRouteImport } from './routes/_autenticado.modulo.validacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadoRoute = AutenticadoRouteImport.update({
  id: '/_autenticado',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadoPainelRoute = AutenticadoPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AutenticadoRoute,
} as any)
const AutenticadoModuloSlugRoute = AutenticadoModuloSlugRouteImport.update({
  id: '/modulo/$slug',
  path: '/modulo/$slug',
  getParentRoute: () => AutenticadoRoute,
} as any)
const AutenticadoModuloAdministracaoRoute =
  AutenticadoModuloAdministracaoRouteImport.update({
    id: '/modulo/administracao',
    path: '/modulo/administracao',
    getParentRoute: () => AutenticadoRoute,
  } as any)
const AutenticadoModuloCaixaRoute = AutenticadoModuloCaixaRouteImport.update({
  id: '/modulo/caixa',
  path: '/modulo/caixa',
  getParentRoute: () => AutenticadoRoute,
} as any)
const AutenticadoModuloEncomendasRoute =
  AutenticadoModuloEncomendasRouteImport.update({
    id: '/modulo/encomendas',
    path: '/modulo/encomendas',
    getParentRoute: () => AutenticadoRoute,
  } as any)
const AutenticadoModuloImoveisRoute =
  AutenticadoModuloImoveisRouteImport.update({
    id: '/modulo/imoveis',
    path: '/modulo/imoveis',
    getParentRoute: () => AutenticadoRoute,
  } as any)
const AutenticadoModuloLogsRoute = AutenticadoModuloLogsRouteImport.update({
  id: '/modulo/logs',
  path: '/modulo/logs',
  getParentRoute: () => AutenticadoRoute,
} as any)
const AutenticadoModuloManutencaoRoute =
  AutenticadoModuloManutencaoRouteImport.update({
    id: '/modulo/manutencao',
    path: '/modulo/manutencao',
    getParentRoute: () => AutenticadoRoute,
  } as any)
const AutenticadoModuloPessoasRoute =
  AutenticadoModuloPessoasRouteImport.update({
    id: '/modulo/pessoas',
    path: '/modulo/pessoas',
    getParentRoute: () => AutenticadoRoute,
  } as any)
const AutenticadoModuloPreCadastroRoute =
  AutenticadoModuloPreCadastroRouteImport.update({
    id: '/modulo/pre-cadastro',
    path: '/modulo/pre-cadastro',
    getParentRoute: () => AutenticadoRoute,
  } as any)
const AutenticadoModuloPrestadoresRoute =
  AutenticadoModuloPrestadoresRouteImport.update({
    id: '/modulo/prestadores',
    path: '/modulo/prestadores',
    getParentRoute: () => AutenticadoRoute,
  } as any)
const AutenticadoModuloRelatoriosRoute =
  AutenticadoModuloRelatoriosRouteImport.update({
    id: '/modulo/relatorios',
    path: '/modulo/relatorios',
    getParentRoute: () => AutenticadoRoute,
  } as any)
const AutenticadoModuloValidacaoRoute =
  AutenticadoModuloValidacaoRouteImport.update({
    id: '/modulo/validacao',
    path: '/modulo/validacao',
    getParentRoute: () => AutenticadoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/painel': typeof AutenticadoPainelRoute
  '/modulo/$slug': typeof AutenticadoModuloSlugRoute
  '/modulo/administracao': typeof AutenticadoModuloAdministracaoRoute
  '/modulo/caixa': typeof AutenticadoModuloCaixaRoute
  '/modulo/encomendas': typeof AutenticadoModuloEncomendasRoute
  '/modulo/imoveis': typeof AutenticadoModuloImoveisRoute
  '/modulo/logs': typeof AutenticadoModuloLogsRoute
  '/modulo/manutencao': typeof AutenticadoModuloManutencaoRoute
  '/modulo/pessoas': typeof AutenticadoModuloPessoasRoute
  '/modulo/pre-cadastro': typeof AutenticadoModuloPreCadastroRoute
  '/modulo/prestadores': typeof AutenticadoModuloPrestadoresRoute
  '/modulo/relatorios': typeof AutenticadoModuloRelatoriosRoute
  '/modulo/validacao': typeof AutenticadoModuloValidacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/painel': typeof AutenticadoPainelRoute
  '/modulo/$slug': typeof AutenticadoModuloSlugRoute
  '/modulo/administracao': typeof AutenticadoModuloAdministracaoRoute
  '/modulo/caixa': typeof AutenticadoModuloCaixaRoute
  '/modulo/encomendas': typeof AutenticadoModuloEncomendasRoute
  '/modulo/imoveis': typeof AutenticadoModuloImoveisRoute
  '/modulo/logs': typeof AutenticadoModuloLogsRoute
  '/modulo/manutencao': typeof AutenticadoModuloManutencaoRoute
  '/modulo/pessoas': typeof AutenticadoModuloPessoasRoute
  '/modulo/pre-cadastro': typeof AutenticadoModuloPreCadastroRoute
  '/modulo/prestadores': typeof AutenticadoModuloPrestadoresRoute
  '/modulo/relatorios': typeof AutenticadoModuloRelatoriosRoute
  '/modulo/validacao': typeof AutenticadoModuloValidacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_autenticado': typeof AutenticadoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/_autenticado/painel': typeof AutenticadoPainelRoute
  '/_autenticado/modulo/$slug': typeof AutenticadoModuloSlugRoute
  '/_autenticado/modulo/administracao': typeof AutenticadoModuloAdministracaoRoute
  '/_autenticado/modulo/caixa': typeof AutenticadoModuloCaixaRoute
  '/_autenticado/modulo/encomendas': typeof AutenticadoModuloEncomendasRoute
  '/_autenticado/modulo/imoveis': typeof AutenticadoModuloImoveisRoute
  '/_autenticado/modulo/logs': typeof AutenticadoModuloLogsRoute
  '/_autenticado/modulo/manutencao': typeof AutenticadoModuloManutencaoRoute
  '/_autenticado/modulo/pessoas': typeof AutenticadoModuloPessoasRoute
  '/_autenticado/modulo/pre-cadastro': typeof AutenticadoModuloPreCadastroRoute
  '/_autenticado/modulo/prestadores': typeof AutenticadoModuloPrestadoresRoute
  '/_autenticado/modulo/relatorios': typeof AutenticadoModuloRelatoriosRoute
  '/_autenticado/modulo/validacao': typeof AutenticadoModuloValidacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/painel'
    | '/modulo/$slug'
    | '/modulo/administracao'
    | '/modulo/caixa'
    | '/modulo/encomendas'
    | '/modulo/imoveis'
    | '/modulo/logs'
    | '/modulo/manutencao'
    | '/modulo/pessoas'
    | '/modulo/pre-cadastro'
    | '/modulo/prestadores'
    | '/modulo/relatorios'
    | '/modulo/validacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/painel'
    | '/modulo/$slug'
    | '/modulo/administracao'
    | '/modulo/caixa'
    | '/modulo/encomendas'
    | '/modulo/imoveis'
    | '/modulo/logs'
    | '/modulo/manutencao'
    | '/modulo/pessoas'
    | '/modulo/pre-cadastro'
    | '/modulo/prestadores'
    | '/modulo/relatorios'
    | '/modulo/validacao'
  id:
    | '__root__'
    | '/'
    | '/_autenticado'
    | '/entrar'
    | '/_autenticado/painel'
    | '/_autenticado/modulo/$slug'
    | '/_autenticado/modulo/administracao'
    | '/_autenticado/modulo/caixa'
    | '/_autenticado/modulo/encomendas'
    | '/_autenticado/modulo/imoveis'
    | '/_autenticado/modulo/logs'
    | '/_autenticado/modulo/manutencao'
    | '/_autenticado/modulo/pessoas'
    | '/_autenticado/modulo/pre-cadastro'
    | '/_autenticado/modulo/prestadores'
    | '/_autenticado/modulo/relatorios'
    | '/_autenticado/modulo/validacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutenticadoRoute: typeof AutenticadoRouteWithChildren
  EntrarRoute: typeof EntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticado': {
      id: '/_autenticado'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AutenticadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticado/painel': {
      id: '/_autenticado/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AutenticadoPainelRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/$slug': {
      id: '/_autenticado/modulo/$slug'
      path: '/modulo/$slug'
      fullPath: '/modulo/$slug'
      preLoaderRoute: typeof AutenticadoModuloSlugRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/administracao': {
      id: '/_autenticado/modulo/administracao'
      path: '/modulo/administracao'
      fullPath: '/modulo/administracao'
      preLoaderRoute: typeof AutenticadoModuloAdministracaoRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/caixa': {
      id: '/_autenticado/modulo/caixa'
      path: '/modulo/caixa'
      fullPath: '/modulo/caixa'
      preLoaderRoute: typeof AutenticadoModuloCaixaRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/encomendas': {
      id: '/_autenticado/modulo/encomendas'
      path: '/modulo/encomendas'
      fullPath: '/modulo/encomendas'
      preLoaderRoute: typeof AutenticadoModuloEncomendasRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/imoveis': {
      id: '/_autenticado/modulo/imoveis'
      path: '/modulo/imoveis'
      fullPath: '/modulo/imoveis'
      preLoaderRoute: typeof AutenticadoModuloImoveisRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/logs': {
      id: '/_autenticado/modulo/logs'
      path: '/modulo/logs'
      fullPath: '/modulo/logs'
      preLoaderRoute: typeof AutenticadoModuloLogsRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/manutencao': {
      id: '/_autenticado/modulo/manutencao'
      path: '/modulo/manutencao'
      fullPath: '/modulo/manutencao'
      preLoaderRoute: typeof AutenticadoModuloManutencaoRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/pessoas': {
      id: '/_autenticado/modulo/pessoas'
      path: '/modulo/pessoas'
      fullPath: '/modulo/pessoas'
      preLoaderRoute: typeof AutenticadoModuloPessoasRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/pre-cadastro': {
      id: '/_autenticado/modulo/pre-cadastro'
      path: '/modulo/pre-cadastro'
      fullPath: '/modulo/pre-cadastro'
      preLoaderRoute: typeof AutenticadoModuloPreCadastroRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/prestadores': {
      id: '/_autenticado/modulo/prestadores'
      path: '/modulo/prestadores'
      fullPath: '/modulo/prestadores'
      preLoaderRoute: typeof AutenticadoModuloPrestadoresRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/relatorios': {
      id: '/_autenticado/modulo/relatorios'
      path: '/modulo/relatorios'
      fullPath: '/modulo/relatorios'
      preLoaderRoute: typeof AutenticadoModuloRelatoriosRouteImport
      parentRoute: typeof AutenticadoRoute
    }
    '/_autenticado/modulo/validacao': {
      id: '/_autenticado/modulo/validacao'
      path: '/modulo/validacao'
      fullPath: '/modulo/validacao'
      preLoaderRoute: typeof AutenticadoModuloValidacaoRouteImport
      parentRoute: typeof AutenticadoRoute
    }
  }
}

interface AutenticadoRouteChildren {
  AutenticadoPainelRoute: typeof AutenticadoPainelRoute
  AutenticadoModuloSlugRoute: typeof AutenticadoModuloSlugRoute
  AutenticadoModuloAdministracaoRoute: typeof AutenticadoModuloAdministracaoRoute
  AutenticadoModuloCaixaRoute: typeof AutenticadoModuloCaixaRoute
  AutenticadoModuloEncomendasRoute: typeof AutenticadoModuloEncomendasRoute
  AutenticadoModuloImoveisRoute: typeof AutenticadoModuloImoveisRoute
  AutenticadoModuloLogsRoute: typeof AutenticadoModuloLogsRoute
  AutenticadoModuloManutencaoRoute: typeof AutenticadoModuloManutencaoRoute
  AutenticadoModuloPessoasRoute: typeof AutenticadoModuloPessoasRoute
  AutenticadoModuloPreCadastroRoute: typeof AutenticadoModuloPreCadastroRoute
  AutenticadoModuloPrestadoresRoute: typeof AutenticadoModuloPrestadoresRoute
  AutenticadoModuloRelatoriosRoute: typeof AutenticadoModuloRelatoriosRoute
  AutenticadoModuloValidacaoRoute: typeof AutenticadoModuloValidacaoRoute
}

const AutenticadoRouteChildren: AutenticadoRouteChildren = {
  AutenticadoPainelRoute: AutenticadoPainelRoute,
  AutenticadoModuloSlugRoute: AutenticadoModuloSlugRoute,
  AutenticadoModuloAdministracaoRoute: AutenticadoModuloAdministracaoRoute,
  AutenticadoModuloCaixaRoute: AutenticadoModuloCaixaRoute,
  AutenticadoModuloEncomendasRoute: AutenticadoModuloEncomendasRoute,
  AutenticadoModuloImoveisRoute: AutenticadoModuloImoveisRoute,
  AutenticadoModuloLogsRoute: AutenticadoModuloLogsRoute,
  AutenticadoModuloManutencaoRoute: AutenticadoModuloManutencaoRoute,
  AutenticadoModuloPessoasRoute: AutenticadoModuloPessoasRoute,
  AutenticadoModuloPreCadastroRoute: AutenticadoModuloPreCadastroRoute,
  AutenticadoModuloPrestadoresRoute: AutenticadoModuloPrestadoresRoute,
  AutenticadoModuloRelatoriosRoute: AutenticadoModuloRelatoriosRoute,
  AutenticadoModuloValidacaoRoute: AutenticadoModuloValidacaoRoute,
}

const AutenticadoRouteWithChildren = AutenticadoRoute._addFileChildren(
  AutenticadoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutenticadoRoute: AutenticadoRouteWithChildren,
  EntrarRoute: EntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
